version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/00-ddl.sql:ro
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    depends_on: [mosquitto, postgres]
    environment:
      - TZ=UTC
      - NODE_RED_ENABLE_PROJECTS=false
      - NODE_RED_ENABLE_SAFE_MODE=false
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC_PREFIX=${MQTT_TOPIC_PREFIX}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ALERT_THROTTLE_SECONDS=${ALERT_THROTTLE_SECONDS}
      - TEMP_THRESHOLD_C=${TEMP_THRESHOLD_C}
      - GFORCE_THRESHOLD=${GFORCE_THRESHOLD}
      - CONSECUTIVE_VIOLATIONS=${CONSECUTIVE_VIOLATIONS}
    ports: ["1880:1880"]
    volumes:
      - ./flows/flows.json:/data/flows.json
      - ./nodered/settings.js:/data/settings.js
      - nodered_data:/data
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      - MB_DB_FILE=/metabase.db
    ports: ["3000:3000"]
    volumes:
      - metabase_data:/metabase.db
    restart: unless-stopped

volumes:
  pgdata: {}
  nodered_data: {}
  metabase_data: {}
